# Generated by Django 3.2.13 on 2022-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='store',
            name='image_alt',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
